name: Main Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    
    - name: Test
      run: |
        export AWS_REGION=us-west-1
        mvn -B install
      env:
        SPRING_CONTENT_VERSION: ${{ secrets.SPRING_CONTENT_VERSION }} 
